name: Azure Web App CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Archive the app to prepare it for deployment
      - name: Archive files
        run: zip -r myapp.zip . -x "*.git*"

      # Deploy to Azure Web App using the Azure CLI
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'daxpower'  # Replace with your Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}  # Set up the Azure Web App Publish Profile as a secret
          package: 'myapp.zip'  # Corrected the package path
